"""Cycloidal Gear Profile Generator (CPG).

Computes the point cloud of a cycloidal gear tooth (external or internal)
and assembles all teeth, the pitch/outer/root circles and the final
positioned gear outline.  It is a drop-in replacement for the involute
generator :mod:`GPG` used by the PGS design tool: the input attributes,
the attribute names and the output arrays are identical, so any code
driving ``GPG`` can drive ``CPG`` unchanged.

Cycloidal tooth geometry
------------------------
The working flank of a cycloidal tooth is built from two cycloids that
meet at the pitch point:

* an **epicycloid** above the pitch circle (addendum flank), generated by
  a point on a rolling circle of radius ``m*A/2`` rolling on the outside
  of the pitch circle, and
* a **hypocycloid** below the pitch circle (dedendum flank), generated by
  a point on a rolling circle of radius ``m*D/2`` rolling on the inside
  of the pitch circle.

For the classic clock-maker design ``rolling radius = pitch radius / 2``
the hypocycloid degenerates to a straight radial line.

Conjugate action for an internal pair (planet inside ring): the planet
addendum flank (epicycloid of the planet pitch circle, rolling radius
``m*A/2``) meshes with the ring DEDENDUM flank, which is an epicycloid of
the ring pitch circle with the same rolling radius; the planet dedendum
flank (hypocycloid, ``m*D/2``) meshes with the ring addendum flank, also
a hypocycloid with the same rolling radius.  (For internal gearing the
flank pairings are epi/epi and hypo/hypo - unlike external gearing's
epi/hypo.)  The generator therefore derives the ring's rolling radii
from the un-swapped addendum/dedendum factors so they match the planet.

The profile shift ``X`` moves the whole tooth radially by ``X*m`` (it
does not change the tooth thickness angle); the backlash ``B`` thins the
tooth by ``B*m`` split over the two flanks.

Input attributes follow common gear conventions (identical to GPG):

    module             pitch-circle-tooth-count ratio (mm / tooth)
    teeth              number of teeth (negative selects internal gear)
    pressure_angle     pressure angle in degrees (dummy, kept for API
                       compatibility; a cycloidal flank has no constant
                       pressure angle)
    shift_factor       profile shift coefficient (X)
    backlash_factor    normalised backlash (B)
    addendum_factor    addendum coefficient (A)
    dedendum_factor    dedendum coefficient (D)
    hob_tip_radius_factor    tip-corner radius of the cutting hob (C)
    tooth_tip_radius_factor  tip-round radius of the tooth itself (E)
    x0, y0                   position offset of the gear centre
    rotate_angle             rotation of the full gear (degrees)
"""

from __future__ import annotations

import numpy as np

ROUND_PRECISION: int = 6


class CPG:
    """Cycloidal gear profile generator (GPG-compatible interface)."""

    def __init__(self) -> None:
        # --- Gear specification ---
        self.module: float = 1.0
        self.teeth: float = -18.0
        self.pressure_angle: float = 20.0
        self.shift_factor: float = 0.0
        self.backlash_factor: float = 0.05
        self.addendum_factor: float = 1.0
        self.dedendum_factor: float = 1.25
        self.hob_tip_radius_factor: float = 0.2
        self.tooth_tip_radius_factor: float = 0.1
        self.x0: float = 0.0
        self.y0: float = 0.0
        self.rotate_angle: float = 0.0
        # --- Segment counts for each domain ---
        self.seg_circle: int = 360
        self.seg_involute: int = 15        # flank sampling (name kept)
        self.seg_edge_round: int = 5
        self.seg_root_round: int = 5
        self.seg_outer: int = 5
        self.seg_root: int = 5
        # --- Calculated parameters (filled by _compute_params) ---
        self.alpha0: float = 0.0          # pressure angle in radians (dummy)
        self.alpha_m: float = 0.0          # half tooth-pitch angle
        self.alpha_is: float = 0.0         # half tooth thickness angle
        self.theta_is: float = 0.0         # flank parameter range start
        self.theta_ie: float = 0.0         # flank parameter range end
        self.alpha_e: float = 0.0          # angle of the tooth's end point
        self.x_e: float = 0.0              # tooth end-point coordinates
        self.y_e: float = 0.0
        self.x_e0: float = 0.0             # edge-round centre coordinates
        self.y_e0: float = 0.0
        self.theta3_min: float = 0.0       # edge-round sweep range
        self.theta3_max: float = 0.0
        self.alpha_ts: float = 0.0         # start angle of the root round
        self.theta_te: float = 0.0         # end angle of the root round
        self.pitch_angle: float = 0.0      # per-tooth pitch angle (rad)
        self.align_angle: float = 0.0      # rotation that aligns tooth to +y
        # --- Cycloidal rolling circle radii ---
        self.roll_radius_add: float = 0.0
        self.roll_radius_ded: float = 0.0
        self.half_thick_pitch: float = 0.0
        # --- Linspaces ---
        self.theta1: np.ndarray = np.empty(0)   # flank parameter
        self.theta3: np.ndarray = np.empty(0)   # edge round
        self.theta_t: np.ndarray = np.empty(0)  # root round
        self.theta_s: np.ndarray = np.empty(0)  # root-round tangent direction
        self.theta6: np.ndarray = np.empty(0)   # outer arc
        self.theta7: np.ndarray = np.empty(0)   # root arc
        # --- Per-tooth curve segments (later concatenated into a tooth) ---
        self.involute_x: np.ndarray = np.empty(0)   # addendum flank points
        self.involute_y: np.ndarray = np.empty(0)
        self.edge_round_x: np.ndarray = np.empty(0)
        self.edge_round_y: np.ndarray = np.empty(0)
        self.root_round_x: np.ndarray = np.empty(0)
        self.root_round_y: np.ndarray = np.empty(0)
        self.outer_arc_x: np.ndarray = np.empty(0)
        self.outer_arc_y: np.ndarray = np.empty(0)
        self.root_arc_x: np.ndarray = np.empty(0)
        self.root_arc_y: np.ndarray = np.empty(0)
        # --- Combined single-tooth geometry ---
        self.half_tooth_x: np.ndarray = np.empty(0)
        self.half_tooth_y: np.ndarray = np.empty(0)
        self.mirror_x: np.ndarray = np.empty(0)
        self.mirror_y: np.ndarray = np.empty(0)
        self.tooth_x: np.ndarray = np.empty(0)
        self.tooth_y: np.ndarray = np.empty(0)
        self.aligned_x: np.ndarray = np.empty(0)
        self.aligned_y: np.ndarray = np.empty(0)
        # --- Full-gear geometry ---
        self.all_teeth_x: np.ndarray = np.empty(0)
        self.all_teeth_y: np.ndarray = np.empty(0)
        self.single_tooth_x: np.ndarray = np.empty(0)
        self.single_tooth_y: np.ndarray = np.empty(0)
        self.rotated_teeth_x: np.ndarray = np.empty(0)
        self.rotated_teeth_y: np.ndarray = np.empty(0)
        self.plot_x: np.ndarray = np.empty(0)   # final positioned outline
        self.plot_y: np.ndarray = np.empty(0)
        # --- Reference circles ---
        self.pitch_circle_radius: float | None = None  # drawn pitch radius override
        self.pitch_circle_x: np.ndarray = np.empty(0)
        self.pitch_circle_y: np.ndarray = np.empty(0)
        self.outer_circle_x: np.ndarray = np.empty(0)
        self.outer_circle_y: np.ndarray = np.empty(0)
        self.root_circle_x: np.ndarray = np.empty(0)
        self.root_circle_y: np.ndarray = np.empty(0)

    # ----------------------------------------------------------- step helpers
    def _apply_internal_convention(self) -> None:
        """Normalise an internal (ring) gear to external-equivalent form.

        Identical to GPG: negates teeth/shift/backlash and swaps
        addendum/dedendum and the two tip-radius coefficients.  Sets the
        ``_is_internal`` flag: the rolling-circle radii of an internal
        gear pair with the mating external gear through the UN-swapped
        addendum/dedendum factors (see _compute_params).
        """
        self._is_internal = self.teeth < 0
        if not self._is_internal:
            return
        self.teeth = -self.teeth
        self.shift_factor = -self.shift_factor
        self.backlash_factor = -self.backlash_factor
        self.addendum_factor, self.dedendum_factor = (
            self.dedendum_factor, self.addendum_factor)
        self.hob_tip_radius_factor, self.tooth_tip_radius_factor = (
            self.tooth_tip_radius_factor, self.hob_tip_radius_factor)

    # ------------------------------------------------------- cycloid curves
    @staticmethod
    def _epicycloid(rp, rr, phi):
        """Point on an epicycloid rolling outside a circle.

        ``rp`` base (pitch) radius, ``rr`` rolling-circle radius, ``phi``
        roll angle (radians).  At ``phi = 0`` the generating point is at
        ``(rp, 0)`` on the base circle; the curve sweeps
        counter-clockwise with growing radius.
        """
        k = rr / rp
        r = rp + rr
        ang = phi * (1.0 + 1.0 / k)
        x = r * np.cos(phi) - rr * np.cos(ang)
        y = r * np.sin(phi) - rr * np.sin(ang)
        return x, y

    @staticmethod
    def _hypocycloid(rp, rr, phi):
        """Point on a hypocycloid rolling inside a circle.

        ``rp`` base (pitch) radius, ``rr`` rolling-circle radius, ``phi``
        roll angle (radians).  At ``phi = 0`` the generating point is at
        ``(rp, 0)`` on the base circle; the curve sweeps
        counter-clockwise with shrinking radius.  For ``rr = rp/2`` the
        curve is a straight radial line.
        """
        k = rr / rp
        r = rp - rr
        ang = phi * (1.0 - 1.0 / k)
        x = r * np.cos(phi) + rr * np.cos(ang)
        y = r * np.sin(phi) - rr * np.sin(ang)
        return x, y

    @staticmethod
    def _polar(x, y):
        """Radius and polar angle (radians, in [0, pi]) of points."""
        rho = np.hypot(x, y)
        psi = np.arctan2(y, x)
        return rho, psi

    def _compute_params(self) -> None:
        """Derive the cycloidal layout angles and rolling circle radii."""
        z = self.teeth
        m = self.module
        self.alpha0 = self.pressure_angle * (2 * np.pi / 360)  # unused, API compat
        rp = m * (z + 2.0 * self.shift_factor) / 2.0             # pitch radius
        self.pitch_angle = 2 * np.pi / z
        self.align_angle = 0.0                 # tooth is built centred on +y
        self.alpha_m = np.pi / z

        # Half tooth thickness angle at the pitch circle: arc rp*ht equals
        # half the tooth thickness (pi*m/4 minus the backlash share).
        ht = np.pi / (2.0 * z) - self.backlash_factor / (2.0 * z)
        self.half_thick_pitch = ht
        self.alpha_is = ht

        # Rolling circle radii.  For conjugate cycloidal action the two
        # flanks of a meshing pair must be generated by the SAME rolling
        # circle:
        #
        #   external pair : gear1 addendum (epicycloid, m*A1/2) meshes
        #                   with gear2 dedendum (hypocycloid, m*A1/2)
        #   internal pair : planet addendum  (epicycloid,  m*A_p/2) meshes
        #                   with the ring DEDENDUM flank - in the
        #                   normalised (swapped) representation the
        #                   addendum flank -> rolling radius m*A_p/2
        #                   planet dedendum  (hypocycloid, m*D_p/2) meshes
        #                   with the ring addendum flank -> rolling
        #                   radius m*D_p/2
        #
        # The internal convention has already swapped the factors, so the
        # ring's rolling radii come from the un-swapped values
        # (dedendum_factor holds the original addendum after the swap).
        if self._is_internal:
            self.roll_radius_add = m * self.dedendum_factor / 2.0
            self.roll_radius_ded = m * self.addendum_factor / 2.0
        else:
            self.roll_radius_add = m * self.addendum_factor / 2.0
            self.roll_radius_ded = m * self.dedendum_factor / 2.0

        rr_a = self.roll_radius_add
        rr_d = self.roll_radius_ded
        r_tip = rp + m * self.addendum_factor
        r_root = rp - m * self.dedendum_factor
        r_tip_eff = r_tip - m * self.tooth_tip_radius_factor
        r_root_eff = r_root + m * self.hob_tip_radius_factor

        def epi_rho(phi):
            x, y = self._epicycloid(rp, rr_a, phi)
            return np.hypot(x, y)

        def epi_psi(phi):
            x, y = self._epicycloid(rp, rr_a, phi)
            return float(np.arctan2(y, x))

        def hypo_rho(phi):
            x, y = self._hypocycloid(rp, rr_d, phi)
            return np.hypot(x, y)

        def hypo_psi(phi):
            x, y = self._hypocycloid(rp, rr_d, phi)
            return float(np.arctan2(y, x))

        # Roll angle where the epicycloid reaches the effective tip radius.
        # The epicycloid radius grows from rp at phi=0 to rp + 2*rr at
        # phi = pi*rr/rp (bisect on this rising half).
        hi = np.pi * rr_a / rp
        target = float(np.clip(r_tip_eff, rp, epi_rho(hi)))
        lo = 0.0
        for _ in range(80):
            mid = 0.5 * (lo + hi)
            if epi_rho(mid) < target:
                lo = mid
            else:
                hi = mid
        self.theta_ie = 0.5 * (lo + hi)

        # Cap the roll angle so the flank's polar sweep stays inside the
        # half tooth thickness angle (the flank must not cross the tooth
        # centre line).
        hi = self.theta_ie
        while hi > 1e-12 and epi_psi(hi) > ht:
            hi *= 0.5
        self.theta_ie = hi

        # Roll angle where the hypocycloid reaches the effective root
        # radius.  The hypocycloid radius shrinks from rp at phi=0 to
        # rp - 2*rr at phi = pi*rr/rp (bisect on this falling half).
        hi = np.pi * rr_d / rp
        target = float(np.clip(r_root_eff, hypo_rho(hi), rp))
        lo = 0.0
        for _ in range(80):
            mid = 0.5 * (lo + hi)
            if hypo_rho(mid) > target:
                lo = mid
            else:
                hi = mid
        self.phi_root = 0.5 * (lo + hi)

        # Cap so the dedendum flank stays on its own side of the pitch
        # point (sweep must not exceed the space half angle pi/z - ht).
        hi = self.phi_root
        while hi > 1e-12 and hypo_psi(hi) > np.pi / z - ht:
            hi *= 0.5
        self.phi_root = hi

        self._rp = rp

        # Tip corner on the tip circle in the flank-end direction, and
        # the ACTUAL flank end (the sweep cap may end the flank before it
        # reaches the tip circle).  The two are joined by a short
        # straight link in _edge_round_curve.
        rho_e = epi_rho(self.theta_ie)
        psi_e = epi_psi(self.theta_ie)
        ang_e = np.pi / 2.0 - ht + psi_e
        self.alpha_e = ang_e
        self.x_e = r_tip * np.cos(ang_e)
        self.y_e = r_tip * np.sin(ang_e)
        self.x_e0 = rho_e * np.cos(ang_e)
        self.y_e0 = rho_e * np.sin(ang_e)

        # Dedendum flank end (root side) angle, for the fillet glue.
        self.alpha_ts = (np.pi / 2.0 - ht) - hypo_psi(self.phi_root)
        self.theta_te = 0.0

    @staticmethod
    def _rotate(x, y, ang):
        ca, sa = np.cos(ang), np.sin(ang)
        return ca * x - sa * y, sa * x + ca * y

    def _flank_curve(self) -> None:
        """Build the half-tooth outline segments in the tooth frame.

        The tooth centre line is the +y axis; the right half of the tooth
        is generated.  Ordered from the tooth centre outwards the segments
        are: outer arc (at r_tip, around +y), edge round or radial link
        (tooth tip corner), addendum flank (epicycloid, down to the pitch
        point), dedendum flank (hypocycloid, down to the fillet), root
        fillet or radial link, root arc (at r_root, out to the space
        centre).

        When the flank cannot reach the tip/root circle within its
        angular room, the remaining radial gap is closed with a straight
        radial line (as on real gear drawings).
        """
        rp = self._rp
        m = self.module
        ht = self.half_thick_pitch
        r_tip = rp + m * self.addendum_factor
        r_root = rp - m * self.dedendum_factor
        rr_a = self.roll_radius_add
        rr_d = self.roll_radius_ded
        base_ang = np.pi / 2.0 - ht          # pitch point angle

        # ---- addendum flank (epicycloid): pitch point -> flank end
        phi = np.linspace(0.0, self.theta_ie, self.seg_involute)
        rho, psi = self._polar(*self._epicycloid(rp, rr_a, phi))
        a_e = base_ang + psi
        self.involute_x = rho * np.cos(a_e)
        self.involute_y = rho * np.sin(a_e)
        self.theta1 = phi

        # ---- dedendum flank (hypocycloid): generated from the root-side
        # end toward the pitch point, so that after _reverse the segment
        # runs pitch point -> root (matching the half-tooth order)
        phi = np.linspace(self.phi_root, 0.0, self.seg_root_round)
        rho, psi = self._polar(*self._hypocycloid(rp, rr_d, phi))
        a_d = base_ang - psi
        self._ded_flank_x = rho * np.cos(a_d)
        self._ded_flank_y = rho * np.sin(a_d)
        self._ded_flank_r = rho
        self._ded_flank_a = a_d

        # ---- root fillet or radial link: from the dedendum flank's
        # root-side end down to the root circle
        rr_c = m * self.hob_tip_radius_factor
        p1 = np.array([self._ded_flank_x[0], self._ded_flank_y[0]])
        r1 = np.hypot(*p1)
        a1 = np.arctan2(p1[1], p1[0])
        t = p1 - np.array([self._ded_flank_x[1], self._ded_flank_y[1]])
        t = t / np.hypot(*t)
        nvec = np.array([t[1], -t[0]])
        if np.dot(nvec, p1) > 0:            # keep the centre toward +y side
            nvec = -nvec
        centre = p1 + rr_c * nvec
        d = np.hypot(*centre)
        if abs(d - r_root) <= rr_c:
            # tangent fillet bridging to the root circle; generated from
            # the flank end toward the root circle (final order)
            a_start = np.arctan2(*(p1 - centre)[::-1])
            cosg = (rr_c ** 2 + d ** 2 - r_root ** 2) / (2 * rr_c * d)
            gamma = np.arccos(np.clip(cosg, -1, 1))
            base = np.arctan2(centre[1], centre[0])
            cand = (base + gamma, base - gamma)
            a_end = min(cand, key=lambda a: abs((a - a_start + np.pi)
                                                % (2 * np.pi) - np.pi))
            sweep = (a_end - a_start + np.pi) % (2 * np.pi) - np.pi
            a = np.linspace(a_start, a_start + sweep, self.seg_root_round)
            self.root_round_x = centre[0] + rr_c * np.cos(a)
            self.root_round_y = centre[1] + rr_c * np.sin(a)
            self.theta_t = a
            self.theta_s = centre
            self.alpha_ts = ang_fillet_root = a_end
        else:
            # radial link: generated from the flank end down to the root
            # circle (final order)
            self.root_round_x = np.linspace(p1[0], r_root * np.cos(a1),
                                            self.seg_root_round)
            self.root_round_y = np.linspace(p1[1], r_root * np.sin(a1),
                                            self.seg_root_round)
            self.theta_t = np.linspace(a1, a1, self.seg_root_round)
            self.theta_s = (0.0, 0.0)
            self.alpha_ts = ang_fillet_root = a1

        # ---- root arc: from the fillet/radial link's root-circle end out
        # to the space centre
        space_ang = np.pi / 2.0 - np.pi / self.teeth
        self.theta7 = np.linspace(space_ang, ang_fillet_root, self.seg_root)
        self.root_arc_x = r_root * np.cos(self.theta7)
        self.root_arc_y = r_root * np.sin(self.theta7)

    def _edge_round_curve(self) -> None:
        """Tip link between the epicycloid flank end and the outer arc:
        a straight segment from the corner (on the tip circle) to the
        actual flank end (generated in the final order corner -> flank
        end)."""
        self.edge_round_x = np.linspace(self.x_e, self.x_e0,
                                        self.seg_edge_round)
        self.edge_round_y = np.linspace(self.y_e, self.y_e0,
                                        self.seg_edge_round)

    def _outer_arc(self) -> None:
        """Arc along the outer (tip) circle from the tooth centre plane
        (+y) out to the tip corner.  The sweep cap on the flank keeps the
        corner on the tooth's own side of the centre line."""
        r_out = self._rp + self.module * self.addendum_factor
        p_edge = np.array([self.edge_round_x[-1], self.edge_round_y[-1]])
        a_start = np.arctan2(p_edge[1], p_edge[0])
        self.theta6 = np.linspace(np.pi / 2.0, a_start, self.seg_outer)
        self.outer_arc_x = r_out * np.cos(self.theta6)
        self.outer_arc_y = r_out * np.sin(self.theta6)

    def _root_arc(self) -> None:
        """Root circle arc (already generated in _flank_curve; kept for
        interface parity with GPG)."""
        pass

    def _reverse(self) -> None:
        """Flip the segment order where needed so the half tooth runs from
        the tooth centre (+y) out to the space centre.

        outer arc, edge round and root arc are generated in the final
        direction; the two flanks are generated inward -> outward and get
        flipped here.
        """
        pairs = (
            (self.involute_x, self.involute_y, "involute_x", "involute_y"),
            (self._ded_flank_x, self._ded_flank_y, "_ded_flank_x", "_ded_flank_y"),
        )
        for x, y, xname, yname in pairs:
            setattr(self, xname, np.flip(x))
            setattr(self, yname, np.flip(y))

    def _combine_half_tooth(self) -> None:
        self.half_tooth_x = np.concatenate((
            self.outer_arc_x, self.edge_round_x, self.involute_x,
            self._ded_flank_x, self.root_round_x, self.root_arc_x))
        self.half_tooth_y = np.concatenate((
            self.outer_arc_y, self.edge_round_y, self.involute_y,
            self._ded_flank_y, self.root_round_y, self.root_arc_y))

    def _mirror_tooth(self) -> None:
        """Mirror the half tooth across the tooth centre line (+y axis):
        (x, y) -> (-x, y), order flipped for continuity."""
        self.mirror_x = -np.flip(self.half_tooth_x)
        self.mirror_y = np.flip(self.half_tooth_y)

    def _combine_tooth(self) -> None:
        self.tooth_x = np.concatenate((self.half_tooth_x, self.mirror_x))
        self.tooth_y = np.concatenate((self.half_tooth_y, self.mirror_y))

    def _align_tooth(self) -> None:
        # the tooth is already centred on +y; nothing to rotate
        self.aligned_x = self.tooth_x
        self.aligned_y = self.tooth_y

    # ----------------------------------------------------------- full gear
    def _build_one_tooth(self) -> None:
        self._apply_internal_convention()
        self._compute_params()
        self._flank_curve()
        self._edge_round_curve()
        self._outer_arc()
        self._root_arc()
        self._reverse()
        self._combine_half_tooth()
        self._mirror_tooth()
        self._combine_tooth()
        self._align_tooth()

    def _build_all_teeth(self) -> None:
        xs = np.empty(0)
        ys = np.empty(0)
        n = int(round(self.teeth, ROUND_PRECISION))
        for i in range(n):
            angle = -self.pitch_angle * i
            ca, sa = np.cos(angle), np.sin(angle)
            xs = np.concatenate((xs, ca * self.aligned_x - sa * self.aligned_y))
            ys = np.concatenate((ys, sa * self.aligned_x + ca * self.aligned_y))
        self.all_teeth_x = xs
        self.all_teeth_y = ys

    def _move_one_tooth(self) -> None:
        self.single_tooth_x = self.aligned_x + self.x0
        self.single_tooth_y = self.aligned_y + self.y0

    def _rotate_all_teeth(self) -> None:
        angle = np.deg2rad(self.rotate_angle)
        ca, sa = np.cos(angle), np.sin(angle)
        self.rotated_teeth_x = ca * self.all_teeth_x - sa * self.all_teeth_y
        self.rotated_teeth_y = sa * self.all_teeth_x + ca * self.all_teeth_y

    def _move_all_teeth(self) -> None:
        self.plot_x = self.rotated_teeth_x + self.x0
        self.plot_y = self.rotated_teeth_y + self.y0

    def _pitch_circle(self) -> None:
        theta = np.linspace(0, 2 * np.pi, self.seg_circle)
        radius = (self.pitch_circle_radius
                  if self.pitch_circle_radius is not None
                  else self.module * (self.teeth / 2 + self.shift_factor))
        self.pitch_circle_x = radius * np.cos(theta) + self.x0
        self.pitch_circle_y = radius * np.sin(theta) + self.y0

    def _outer_circle(self) -> None:
        theta = np.linspace(0, 2 * np.pi, self.seg_circle)
        radius = self.module * (self.teeth + self.shift_factor) / 2 + self.module * self.addendum_factor
        self.outer_circle_x = radius * np.cos(theta) + self.x0
        self.outer_circle_y = radius * np.sin(theta) + self.y0

    def _root_circle(self) -> None:
        theta = np.linspace(0, 2 * np.pi, self.seg_circle)
        radius = self.module * (self.teeth + self.shift_factor) / 2 - self.module * self.dedendum_factor
        self.root_circle_x = radius * np.cos(theta) + self.x0
        self.root_circle_y = radius * np.sin(theta) + self.y0

    def calc(self) -> None:
        """Generate the complete gear outline and reference circles."""
        self._build_one_tooth()
        self._build_all_teeth()
        self._move_one_tooth()
        self._rotate_all_teeth()
        self._move_all_teeth()
        self._pitch_circle()
        self._outer_circle()
        self._root_circle()
