"""Cycloidal Gear Profile Generator (CPG).

Computes the point cloud of a cycloidal gear tooth (external or internal)
and assembles all teeth, the pitch/outer/root circles and the final
positioned gear outline.  It is a drop-in replacement for the involute
generator :mod:`GPG` used by the PGS design tool: the input attributes,
the attribute names and the output arrays are identical, so any code
driving ``GPG`` can drive ``CPG`` unchanged.

Cycloidal tooth geometry
------------------------
A cycloidal flank is the trace of a point on a *rolling circle* that rolls
without slipping on the pitch circle:

* an **epicycloid** is generated by rolling on the outside of the pitch
  circle and forms the addendum (tip-side) flank,
* a **hypocycloid** is generated by rolling on the inside of the pitch
  circle and forms the dedendum (root-side) flank.

Both share the same rolling radius ``r = gen_ratio * m / 2``.  With the
pitch radius ``R`` and roll angle ``phi`` the two curves are

    epi :  x + iy = e^{iA} [(R + r) - r e^{i phi}]
    hypo:  x + iy = e^{-iA}[(R - r) + r e^{i phi}],   A = r phi / R

whose closed-form radii (used to truncate the flanks at the tip/root
circles) are

    rho_e(phi) = sqrt((R + r)^2 + r^2 - 2 r (R + r) cos(phi))
    rho_i(phi) = sqrt(R^2 - 4 r (R - r) sin^2(phi / 2))

The two flanks meet at the pitch point where the tooth is tangent to the
pitch circle (a cusp of zero rolling speed).  A tip round (radius ``E*m``)
and a root round (radius ``C*m``) join the flanks to the tip/root circles.
The tooth is symmetric about its centre line, mirrored and then arrayed
``z`` times around the gear.

References
----------
* https://tro.kr/3  (cycloid curve theory and gear construction)
* ``example.py``  (``cycloid_gear.py`` reference implementation whose
  curve/fillet helpers are ported below)

Input attributes follow common gear conventions (identical to GPG):

    module             pitch-circle-tooth-count ratio (mm / tooth)
    teeth              number of teeth (negative selects internal gear)
    pressure_angle     pressure angle in degrees (dummy, kept for API
                       compatibility; a cycloidal flank has no constant
                       pressure angle)
    shift_factor       profile shift coefficient (X)
    backlash_factor    normalised backlash (B)
    addendum_factor    addendum coefficient (A)
    dedendum_factor    dedendum coefficient (D)
    hob_tip_radius_factor    tip-corner radius of the cutting hob (C)
    tooth_tip_radius_factor  tip-round radius of the tooth itself (E)
    gen_ratio          rolling-circle diameter / module (Pd/m, CPG only)
    x0, y0                   position offset of the gear centre
    rotate_angle             rotation of the full gear (degrees)
"""

from __future__ import annotations

import math

import numpy as np

ROUND_PRECISION: int = 6
TAU: float = 2.0 * math.pi


# ---------------------------------------------------------------- cycloid curves
def _epicycloid(phi: np.ndarray, rp: float, r: float) -> np.ndarray:
    """Epicycloid points (Nx2): rolling circle radius ``r`` outside pitch ``rp``.

    ``phi`` is the roll angle; at ``phi = 0`` the generating point is at the
    pitch point ``(rp, 0)`` and the curve sweeps counter-clockwise with
    growing radius.
    """
    A = r * phi / rp
    return np.stack(
        [(rp + r) * np.cos(A) - r * np.cos(A + phi),
         (rp + r) * np.sin(A) - r * np.sin(A + phi)], axis=1)


def _hypocycloid(phi: np.ndarray, rp: float, r: float) -> np.ndarray:
    """Hypocycloid points (Nx2): rolling circle radius ``r`` inside pitch ``rp``.

    At ``phi = 0`` the generating point is at ``(rp, 0)`` and the curve
    sweeps clockwise with shrinking radius.
    """
    A = r * phi / rp
    return np.stack(
        [(rp - r) * np.cos(A) + r * np.cos(phi - A),
         -(rp - r) * np.sin(A) + r * np.sin(phi - A)], axis=1)


# ---------------------------------------------------------------- drawing helpers
def _arc_origin(rho: float, a0: float, a1: float, n: int = 32) -> np.ndarray:
    """Circular arc centred on the origin from angle ``a0`` to ``a1``."""
    a = np.linspace(a0, a1, n)
    return np.stack([rho * np.cos(a), rho * np.sin(a)], axis=1)


def _arc_center(C, rho: float, P0, P1, n: int = 24) -> np.ndarray:
    """Circular arc centred at ``C`` from the direction of ``P0`` to ``P1``."""
    a0 = math.atan2(P0[1] - C[1], P0[0] - C[0])
    a1 = math.atan2(P1[1] - C[1], P1[0] - C[0])
    while a1 - a0 > math.pi:
        a1 -= TAU
    while a1 - a0 < -math.pi:
        a1 += TAU
    a = np.linspace(a0, a1, n)
    return np.stack([C[0] + rho * np.cos(a), C[1] + rho * np.sin(a)], axis=1)


def _rot(P: np.ndarray, th: float) -> np.ndarray:
    """Rotate Nx2 point array by angle ``th``."""
    c, s = math.cos(th), math.sin(th)
    return P @ np.array([[c, -s], [s, c]])


def _fillet(P: np.ndarray, rho: float, centre_radius: float,
            r_circle: float, side: int = 1):
    """Tangent fillet of radius ``rho`` between curve ``P`` and circle ``r_circle``.

    ``P`` runs pitch-point -> flank end over the FULL flank (down to the
    tip/root circle) so the tangency always exists on the correct side.
    ``centre_radius`` is the distance of the fillet centre from the origin
    (``r_circle - rho`` for the tip round, ``r_root + rho`` for the root
    round) and ``r_circle`` the radius of the circle being joined.  ``side``
    selects the offset normal: ``+1`` = ``rotate(tangent, +90deg)``, which
    places the centre on the correct (material / space) side for both the
    epicycloid tip round and the hypocycloid root round.

    Returns ``{"cut", "Pt", "C", "Pc"}``: the tangency index on ``P``, the
    tangency point on the curve, the fillet centre and the tangency point on
    the circle, or ``None`` when the fillet cannot be built.
    """
    if rho is None or rho <= 0 or len(P) < 4:
        return None
    d = np.zeros_like(P)
    v = P[2:] - P[:-2]
    d[1:-1] = v / np.linalg.norm(v, axis=1, keepdims=True)
    d[0], d[-1] = d[1], d[-2]
    nrm = side * np.stack([-d[:, 1], d[:, 0]], axis=1)   # offset normal
    C = P + rho * nrm
    g = np.hypot(C[:, 0], C[:, 1]) - centre_radius
    for i in range(len(P) - 1, 0, -1):                    # scan from the end back
        if g[i - 1] * g[i] < 0:
            t = g[i - 1] / (g[i - 1] - g[i])
            Cc = C[i - 1] + t * (C[i] - C[i - 1])         # fillet centre (approx)
            n = nrm[i - 1] + t * (nrm[i] - nrm[i - 1])
            n = n / np.linalg.norm(n)
            u = Cc / np.linalg.norm(Cc)
            Cc = centre_radius * u                        # snap to exact centre radius
            Pt = Cc - rho * n                             # tangency on the curve
            Pc = r_circle * u                             # tangency on the circle
            return {"cut": i, "Pt": Pt, "C": Cc, "Pc": Pc}
    return None


class CPG:
    """Cycloidal gear profile generator (GPG-compatible interface)."""

    def __init__(self) -> None:
        # --- Gear specification ---
        self.module: float = 1.0
        self.teeth: float = -18.0
        self.pressure_angle: float = 20.0
        self.shift_factor: float = 0.0
        self.backlash_factor: float = 0.05
        self.addendum_factor: float = 1.0
        self.dedendum_factor: float = 1.25
        self.hob_tip_radius_factor: float = 0.2
        self.tooth_tip_radius_factor: float = 0.1
        self.gen_ratio: float = 3.0          # rolling-circle diameter / module
        self.x0: float = 0.0
        self.y0: float = 0.0
        self.rotate_angle: float = 0.0
        # --- Segment counts for each domain ---
        self.seg_circle: int = 360
        self.seg_involute: int = 15          # flank sampling (name kept)
        self.seg_edge_round: int = 5
        self.seg_root_round: int = 5
        self.seg_outer: int = 5
        self.seg_root: int = 5
        # --- Calculated parameters ---
        self.alpha0: float = 0.0             # pressure angle in radians (dummy)
        self.alpha_m: float = 0.0            # half tooth-pitch angle
        self.alpha_is: float = 0.0           # half tooth thickness angle
        self.theta_is: float = 0.0
        self.theta_ie: float = 0.0           # addendum flank roll-angle end
        self.alpha_e: float = 0.0
        self.x_e: float = 0.0
        self.y_e: float = 0.0
        self.x_e0: float = 0.0
        self.y_e0: float = 0.0
        self.theta3_min: float = 0.0
        self.theta3_max: float = 0.0
        self.alpha_ts: float = 0.0
        self.theta_te: float = 0.0
        self.pitch_angle: float = 0.0        # per-tooth pitch angle (rad)
        self.align_angle: float = 0.0        # rotation aligning the tooth
        self._is_internal: bool = False
        # --- Cycloidal layout ---
        self._rp: float = 0.0                # pitch radius
        self._r_roll: float = 0.0            # rolling-circle radius
        self._r_tip: float = 0.0
        self._r_root: float = 0.0
        self._re: float = 0.0                # tip-round radius
        self._rc: float = 0.0                # root-round radius
        self._phi_tip: float = 0.0           # epicycloid roll-angle end
        self._phi_root: float = 0.0          # hypocycloid roll-angle end
        # --- Per-tooth curve segments ---
        self.involute_x: np.ndarray = np.empty(0)   # cycloid flank (epi + hypo)
        self.involute_y: np.ndarray = np.empty(0)
        self.edge_round_x: np.ndarray = np.empty(0)
        self.edge_round_y: np.ndarray = np.empty(0)
        self.root_round_x: np.ndarray = np.empty(0)
        self.root_round_y: np.ndarray = np.empty(0)
        self.outer_arc_x: np.ndarray = np.empty(0)
        self.outer_arc_y: np.ndarray = np.empty(0)
        self.root_arc_x: np.ndarray = np.empty(0)
        self.root_arc_y: np.ndarray = np.empty(0)
        # --- Combined single-tooth geometry ---
        self.half_tooth_x: np.ndarray = np.empty(0)
        self.half_tooth_y: np.ndarray = np.empty(0)
        self.mirror_x: np.ndarray = np.empty(0)
        self.mirror_y: np.ndarray = np.empty(0)
        self.tooth_x: np.ndarray = np.empty(0)
        self.tooth_y: np.ndarray = np.empty(0)
        self.aligned_x: np.ndarray = np.empty(0)
        self.aligned_y: np.ndarray = np.empty(0)
        # --- Full-gear geometry ---
        self.all_teeth_x: np.ndarray = np.empty(0)
        self.all_teeth_y: np.ndarray = np.empty(0)
        self.single_tooth_x: np.ndarray = np.empty(0)
        self.single_tooth_y: np.ndarray = np.empty(0)
        self.rotated_teeth_x: np.ndarray = np.empty(0)
        self.rotated_teeth_y: np.ndarray = np.empty(0)
        self.plot_x: np.ndarray = np.empty(0)   # final positioned outline
        self.plot_y: np.ndarray = np.empty(0)
        # --- Reference circles ---
        self.pitch_circle_radius: float | None = None  # drawn pitch radius override
        self.pitch_circle_x: np.ndarray = np.empty(0)
        self.pitch_circle_y: np.ndarray = np.empty(0)
        self.outer_circle_x: np.ndarray = np.empty(0)
        self.outer_circle_y: np.ndarray = np.empty(0)
        self.root_circle_x: np.ndarray = np.empty(0)
        self.root_circle_y: np.ndarray = np.empty(0)

    # ----------------------------------------------------------- step helpers
    def _apply_internal_convention(self) -> None:
        """Normalise an internal (ring) gear to external-equivalent form.

        Identical to GPG: negates teeth/shift/backlash and swaps
        addendum/dedendum and the two tip-radius coefficients so the same
        tooth-generation math can be reused for ring gears.
        """
        self._is_internal = self.teeth < 0
        if not self._is_internal:
            return
        self.teeth = -self.teeth
        self.shift_factor = -self.shift_factor
        self.backlash_factor = -self.backlash_factor
        self.addendum_factor, self.dedendum_factor = (
            self.dedendum_factor, self.addendum_factor)
        self.hob_tip_radius_factor, self.tooth_tip_radius_factor = (
            self.tooth_tip_radius_factor, self.hob_tip_radius_factor)

    def _compute_params(self) -> None:
        """Derive the cycloidal layout radii and roll-angle limits."""
        z = self.teeth
        m = self.module
        X = self.shift_factor
        B = self.backlash_factor
        A = self.addendum_factor
        D = self.dedendum_factor
        C = self.hob_tip_radius_factor
        E = self.tooth_tip_radius_factor

        self.alpha0 = self.pressure_angle * (2 * np.pi / 360)  # unused, API compat
        self.pitch_angle = 2 * np.pi / z
        self.alpha_m = np.pi / z

        # Tooth angular half-thickness at the pitch circle.  For a cycloidal
        # gear the circular thickness at the pitch circle is
        #     (2 * t_half) * rp = (pi/2 - B) * m
        # i.e. it is made INDEPENDENT of the profile shift ``X`` (effective
        # tooth count ``z + 2X``).  This is essential: with the old ``pi/(2z)``
        # the thickness grew with X, so two equally-shifted mating gears both
        # thickened and jammed.  Backlash is folded into t_half instead of
        # rotating the flanks, because rotating a cycloid detaches it from the
        # pitch point and destroys conjugacy.
        zeff = z + 2.0 * X
        self._t_half = (np.pi / 2.0 - B) / zeff

        self.align_angle = np.pi / 2 - self._t_half  # tooth centre -> +y

        if self.pitch_circle_radius is not None:
            # Internal ring gears: the layout fixes the pitch radius (it must
            # satisfy the carrier/centre-distance), override the shifted value.
            rp = self.pitch_circle_radius
        else:
            rp = m * (z / 2 + X)
        r = 0.5 * self.gen_ratio * m
        r_tip = rp + A * m
        r_root = rp - D * m
        re = E * m
        rc = C * m

        if r_root <= 0:
            raise ValueError("잇수가 너무 적습니다 (이뿌리원 반지름 <= 0).")
        if rp <= r:
            raise ValueError("창성원이 너무 큽니다 (rp > r 여야 합니다).")
        if r_tip > rp + 2 * r:
            raise ValueError("창성원이 너무 작습니다 (이끝원에 도달 불가: gen_ratio 를 키우세요).")
        if r_root < rp - 2 * r:
            raise ValueError("창성원이 너무 작습니다 (이뿌리원에 도달 불가: gen_ratio 를 키우세요).")
        if re >= A * m:
            raise ValueError("이끝 모깎기 반지름이 어덴덤보다 큽니다.")
        if rc >= D * m:
            raise ValueError("이뿌리 모깎기 반지름이 디덴덤보다 큽니다.")

        self._rp = rp
        self._r_roll = r
        self._r_tip = r_tip
        self._r_root = r_root
        self._re = re
        self._rc = rc

        # Closed-form roll angles where each flank meets the tip / root
        # circle.  The flanks are generated over these FULL ranges so the
        # fillet search (_fillet) can find the tangency on the material
        # side; the portions beyond the tangency are trimmed afterwards.
        cos_t = ((rp + r) ** 2 + r ** 2 - r_tip ** 2) / (2 * r * (rp + r))
        self._phi_tip = float(np.arccos(np.clip(cos_t, -1.0, 1.0)))
        s2 = (rp ** 2 - r_root ** 2) / (4 * r * (rp - r))
        self._phi_root = 2.0 * float(np.arcsin(np.sqrt(np.clip(s2, 0.0, 1.0))))

        self.theta_ie = self._phi_tip
        self.theta_te = self._phi_root

    def _fit_round(self, P, rho, centre_radius, r_circle, th_limit, is_tip):
        """Shrink a round radius ``rho`` until its tangency fits the tooth.

        Returns ``(rho_eff, fillet)`` where ``fillet`` is from :func:`_fillet`.
        The tip round must keep its circle tangency below ``th_limit``
        (``a_t < th_tooth``); the root round must keep it above ``th_limit``
        (``a_c > th_space``).  When the requested radius overruns the flank it
        is reduced (85% steps) instead of raising, so a valid -- if slightly
        smaller -- round is always produced.
        """
        rho_eff = rho
        f = None
        for _ in range(40):
            if rho_eff <= 1e-9:
                break
            f = _fillet(P, rho_eff, centre_radius, r_circle, side=+1)
            if f is None:
                break
            a = math.atan2(f["Pc"][1], f["Pc"][0])
            if (a < th_limit) if is_tip else (a > th_limit):
                break
            rho_eff *= 0.85
            centre_radius = (r_circle - rho_eff) if is_tip else (r_circle + rho_eff)
        return rho_eff, f

    def _build_tooth_segments(self) -> None:
        """Build the half-tooth outline (space centre -> tooth centre).

        Segments, in order: root arc, root round, hypocycloid, epicycloid,
        tip round, tip arc.  The half tooth is mirrored in ``_mirror_tooth``.
        """
        z = self.teeth
        rp = self._rp
        r = self._r_roll
        r_tip = self._r_tip
        r_root = self._r_root
        re = self._re
        rc = self._rc
        n = self.seg_involute

        th_space = -self._t_half
        th_tooth = self._t_half
        dback = 0.0   # backlash is already in self._t_half

        # Raw cycloid curves (pitch point at angle 0).  The flanks are NOT
        # rotated for backlash: rotating a cycloid moves it off the pitch point
        # and breaks the conjugate action that makes cycloidal gears mesh.
        epi = _epicycloid(np.linspace(0.0, self._phi_tip, n), rp, r)
        hypo = _hypocycloid(np.linspace(0.0, self._phi_root, n), rp, r)

        # Tip / root rounds.  When the requested round radius overruns the
        # tooth (its tangency would cross the tooth centre line) the radius is
        # shrunk until it fits instead of aborting -- a slightly smaller round
        # is always preferable to a hard failure (e.g. on internal gears).
        re_eff, ft = self._fit_round(epi, re, r_tip - re, r_tip, th_tooth, True)
        rc_eff, fr = self._fit_round(hypo, rc, r_root + rc, r_root, th_space, False)

        parts = []

        # (1) root arc + root round + hypocycloid
        if fr:
            a_c = math.atan2(fr["Pc"][1], fr["Pc"][0])
            root_arc = _arc_origin(r_root, th_space, a_c, self.seg_root)
            root_round = _arc_center(fr["C"], rc_eff, fr["Pc"], fr["Pt"], self.seg_root_round)
            flank = np.vstack([hypo[:fr["cut"]], fr["Pt"]])[::-1]
        else:
            a_c = math.atan2(hypo[-1][1], hypo[-1][0])
            root_arc = _arc_origin(r_root, th_space, a_c, self.seg_root)
            root_round = np.empty((0, 2))
            flank = hypo[::-1]
        parts.append(root_arc)
        parts.append(root_round)
        parts.append(flank)                        # hypocycloid (root -> pitch)

        # (2) epicycloid + tip round + tip arc
        if ft:
            tip_flank = np.vstack([epi[:ft["cut"]], ft["Pt"]])
            a_t = math.atan2(ft["Pc"][1], ft["Pc"][0])
            tip_round = _arc_center(ft["C"], re_eff, ft["Pt"], ft["Pc"], self.seg_edge_round)
            tip_arc = _arc_origin(r_tip, a_t, th_tooth, self.seg_outer)
        else:
            tip_flank = epi
            tip_round = np.empty((0, 2))
            tip_arc = _arc_origin(r_tip, math.atan2(epi[-1][1], epi[-1][0]),
                                  th_tooth, self.seg_outer)
        parts.append(tip_flank)                    # epicycloid (pitch -> tip)
        parts.append(tip_round)
        parts.append(tip_arc)

        H = np.vstack(parts)
        self.half_tooth_x = H[:, 0]
        self.half_tooth_y = H[:, 1]

        # Per-segment arrays (interface parity with GPG; flank = hypo + epi).
        self.root_arc_x, self.root_arc_y = root_arc[:, 0], root_arc[:, 1]
        if root_round.size:
            self.root_round_x, self.root_round_y = root_round[:, 0], root_round[:, 1]
        else:
            self.root_round_x = self.root_round_y = np.empty(0)
        flank = np.vstack([flank, tip_flank])
        self.involute_x, self.involute_y = flank[:, 0], flank[:, 1]
        if tip_round.size:
            self.edge_round_x, self.edge_round_y = tip_round[:, 0], tip_round[:, 1]
        else:
            self.edge_round_x = self.edge_round_y = np.empty(0)
        self.outer_arc_x, self.outer_arc_y = tip_arc[:, 0], tip_arc[:, 1]

    def _mirror_tooth(self) -> None:
        """Mirror the half tooth across the tooth centre line (angle t_half)."""
        a = self._t_half
        c2, s2 = math.cos(2 * a), math.sin(2 * a)
        mx = self.half_tooth_x * c2 + self.half_tooth_y * s2
        my = self.half_tooth_x * s2 - self.half_tooth_y * c2
        self.mirror_x = mx[::-1]
        self.mirror_y = my[::-1]

    def _combine_tooth(self) -> None:
        self.tooth_x = np.concatenate((self.half_tooth_x, self.mirror_x))
        self.tooth_y = np.concatenate((self.half_tooth_y, self.mirror_y))

    def _align_tooth(self) -> None:
        ang = self.align_angle
        ca, sa = np.cos(ang), np.sin(ang)
        self.aligned_x = ca * self.tooth_x - sa * self.tooth_y
        self.aligned_y = sa * self.tooth_x + ca * self.tooth_y

    # ----------------------------------------------------------- full gear
    def _build_one_tooth(self) -> None:
        self._apply_internal_convention()
        self._compute_params()
        self._build_tooth_segments()
        self._mirror_tooth()
        self._combine_tooth()
        self._align_tooth()

    def _build_all_teeth(self) -> None:
        """Assemble all teeth into one continuous outline.

        Each tooth spans exactly one pitch period (its start and end lie on
        the root circle at the neighbouring space centres).  Appending the
        teeth in array order with a plain rotation would leave a long chord
        jumping across the gear between consecutive teeth (and visually
        skipping teeth).  Reversing every tooth before concatenation makes
        tooth ``i`` end exactly where tooth ``i + 1`` begins, so the full
        point array is a single gapless loop -- start and end of each tooth
        connect to the next, with no stray connecting line.
        """
        xs = np.empty(0)
        ys = np.empty(0)
        n = int(round(self.teeth, ROUND_PRECISION))
        for i in range(n):
            angle = -self.pitch_angle * i
            ca, sa = np.cos(angle), np.sin(angle)
            rx = ca * self.aligned_x - sa * self.aligned_y
            ry = sa * self.aligned_x + ca * self.aligned_y
            xs = np.concatenate((xs, rx[::-1]))
            ys = np.concatenate((ys, ry[::-1]))
        # Close the loop: the last point is one segment away from the first
        # point across the final tooth/space junction.  Appending the first
        # vertex lets plt.plot draw that closing segment like every other
        # junction, so the outline is continuous all the way around.
        self.all_teeth_x = np.append(xs, xs[0])
        self.all_teeth_y = np.append(ys, ys[0])

    def _move_one_tooth(self) -> None:
        self.single_tooth_x = self.aligned_x + self.x0
        self.single_tooth_y = self.aligned_y + self.y0

    def _rotate_all_teeth(self) -> None:
        angle = np.deg2rad(self.rotate_angle)
        ca, sa = np.cos(angle), np.sin(angle)
        self.rotated_teeth_x = ca * self.all_teeth_x - sa * self.all_teeth_y
        self.rotated_teeth_y = sa * self.all_teeth_x + ca * self.all_teeth_y

    def _move_all_teeth(self) -> None:
        self.plot_x = self.rotated_teeth_x + self.x0
        self.plot_y = self.rotated_teeth_y + self.y0

    def _pitch_circle(self) -> None:
        theta = np.linspace(0, 2 * np.pi, self.seg_circle)
        radius = (self.pitch_circle_radius
                  if self.pitch_circle_radius is not None
                  else self.module * (self.teeth / 2 + self.shift_factor))
        self.pitch_circle_x = radius * np.cos(theta) + self.x0
        self.pitch_circle_y = radius * np.sin(theta) + self.y0

    def _outer_circle(self) -> None:
        theta = np.linspace(0, 2 * np.pi, self.seg_circle)
        self.outer_circle_x = self._r_tip * np.cos(theta) + self.x0
        self.outer_circle_y = self._r_tip * np.sin(theta) + self.y0

    def _root_circle(self) -> None:
        theta = np.linspace(0, 2 * np.pi, self.seg_circle)
        self.root_circle_x = self._r_root * np.cos(theta) + self.x0
        self.root_circle_y = self._r_root * np.sin(theta) + self.y0

    def calc(self) -> None:
        """Generate the complete gear outline and reference circles."""
        self._build_one_tooth()
        self._build_all_teeth()
        self._move_one_tooth()
        self._rotate_all_teeth()
        self._move_all_teeth()
        self._pitch_circle()
        self._outer_circle()
        self._root_circle()
